import './style.css';
const API_BASE=(globalThis.__SUPERDEAL_API__||'').replace(/\/$/,'');
const filters=[['trending','🔥','Trending'],['drops','📉','Price drops'],['under499','₹','Under ₹499'],['discount','%','50%+ off'],['ending','⏳','Ending soon']];
const state={deals:[],active:'trending',saved:new Set(JSON.parse(localStorage.getItem('superdeal-saved')||'[]')),intel:new Map()};
const app=document.querySelector('#app');
app.innerHTML=`<header class="topbar"><div class="brand-mark"><span class="logo-dot"></span><div><div class="brand">SuperDeal</div><div class="tagline">Deals worth your click.</div></div></div><button class="circle-btn" aria-label="Notifications">♧</button></header><main><section class="hero"><div class="eyebrow">TODAY'S PICKS</div><h1>Spend less.<br><span>Get more.</span></h1><p>Fresh deals, price drops and genuine finds — all in one place.</p></section><section class="search-wrap"><span class="search-icon">⌕</span><input id="search" type="search" placeholder="Search products, brands or deals" autocomplete="off"><button id="clear" class="clear hidden" aria-label="Clear search">×</button></section><section class="chips" aria-label="Deal filters">${filters.map(([id,icon,label],i)=>`<button class="chip ${i===0?'selected':''}" data-filter="${id}"><b>${icon}</b>${label}</button>`).join('')}</section><section class="section-head"><div><div class="eyebrow">CURATED FOR YOU</div><h2 id="section-title">Trending now</h2></div><span id="count"></span></section><section id="deals" class="deal-grid" aria-live="polite"></section></main><nav class="bottom-nav"><button class="active" data-nav="home"><span>⌂</span>Home</button><button data-nav="search"><span>⌕</span>Search</button><button data-nav="saved"><span>♡</span>Saved</button></nav><div id="toast" class="toast" role="status"></div><div id="detail" class="detail hidden"></div>`;
const dealsEl=document.querySelector('#deals'),countEl=document.querySelector('#count'),searchEl=document.querySelector('#search'),clearEl=document.querySelector('#clear'),sectionTitle=document.querySelector('#section-title'),toast=document.querySelector('#toast'),detail=document.querySelector('#detail');
const money=v=>v==null?'Check price':`₹${Number(v).toLocaleString('en-IN')}`;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(d){const saved=state.saved.has(String(d.id)),i=state.intel.get(d.id),drop=i&&i.change_pct<0,low=i?.is_historical_low;return `<article class="deal-card" data-open="${esc(d.id)}"><div class="image-wrap"><img src="${esc(d.image_url||'https://placehold.co/320x260?text=SuperDeal')}" alt="${esc(d.product_name)}" loading="lazy"><button class="save ${saved?'saved':''}" data-save="${esc(d.id)}" aria-label="${saved?'Remove from saved':'Save deal'}">${saved?'♥':'♡'}</button>${d.discount_pct?`<span class="badge">${esc(d.discount_pct)}% OFF</span>`:''}${drop?'<span class="drop-badge">PRICE DROP</span>':''}</div><div class="card-content"><div class="merchant">${esc(d.merchant||'SuperDeal find')}</div><h3>${esc(d.product_name)}</h3><div class="price-line"><strong>${money(d.current_price)}</strong>${low?'<span class="low">★ Lowest seen</span>':d.verified_price?'<span class="verified">✓ Verified</span>':''}</div><div class="card-footer"><button class="get-deal" data-open="${esc(d.id)}">View deal <span>↗</span></button><button class="share" data-share="${esc(d.id)}" aria-label="Share deal">⌁</button></div></div></article>`}
function render(list){countEl.textContent=`${list.length} finds`;dealsEl.innerHTML=list.length?list.map(card).join(''):'<div class="empty"><div>✦</div><strong>No deals found</strong><p>Try another product or filter.</p></div>';}
function filtered(){const q=searchEl.value.trim().toLowerCase();let list=state.deals.filter(d=>!q||String(d.product_name).toLowerCase().includes(q)||String(d.merchant||'').toLowerCase().includes(q));if(state.active==='under499')list=list.filter(d=>d.current_price!=null&&d.current_price<500);if(state.active==='discount')list=list.filter(d=>Number(d.discount_pct||0)>=50);if(state.active==='drops')list=list.filter(d=>state.intel.get(d.id)?.change_pct<0);if(state.active==='ending')list=list.filter(d=>{const t=Date.parse(d.last_seen_at);return t&&Date.now()-t<24*3600e3});if(state.active==='saved')list=list.filter(d=>state.saved.has(String(d.id)));return list;}
async function loadIntelligence(list){await Promise.all(list.map(async d=>{if(state.intel.has(d.id))return;try{const r=await fetch(`${API_BASE}/deals/${d.id}/intelligence`);if(r.ok)state.intel.set(d.id,await r.json())}catch{}}));render(filtered());}
async function load(){dealsEl.innerHTML='<div class="skeleton-grid">'+Array.from({length:4},()=>'<div class="skeleton"></div>').join('');try{const r=await fetch(`${API_BASE}/deals?limit=30`);if(!r.ok)throw 0;state.deals=(await r.json()).deals||[];render(filtered());loadIntelligence(state.deals)}catch{countEl.textContent='';dealsEl.innerHTML='<div class="empty"><div>⚡</div><strong>We are warming up.</strong><p>Live deals will appear here once the API is connected.</p></div>'}}
function showDetail(id){const d=state.deals.find(x=>String(x.id)===String(id));if(!d)return;const i=state.intel.get(d.id);detail.innerHTML=`<div class="detail-sheet"><button class="detail-close" data-close>×</button><div class="detail-image"><img src="${esc(d.image_url||'https://placehold.co/500x400?text=SuperDeal')}" alt="${esc(d.product_name)}"></div><div class="eyebrow">${esc(d.merchant||'SUPERDEAL')}</div><h2>${esc(d.product_name)}</h2><div class="detail-price">${money(d.current_price)}</div><div class="insights">${i?.is_historical_low?'<span>★ Historical low</span>':''}${i?.change_pct<0?`<span>↓ ${Math.abs(i.change_pct)}% vs previous</span>`:''}${d.discount_pct?`<span>${d.discount_pct}% off</span>`:''}${d.verified_price?'<span>✓ Price verified</span>':''}</div><div class="detail-stats"><div><b>${i?.lowest_price!=null?money(i.lowest_price):'—'}</b><small>Lowest seen</small></div><div><b>${i?.highest_price!=null?money(i.highest_price):'—'}</b><small>Highest seen</small></div><div><b>${i?.observations??0}</b><small>Observations</small></div></div><p class="detail-note">Prices and availability can change. Check the merchant page before buying.</p><a class="detail-cta" href="${esc(d.affiliate_url||d.source_url||'#')}" target="_blank" rel="noopener">Get this deal ↗</a></div>`;detail.classList.remove('hidden');document.body.classList.add('modal-open')}
function closeDetail(){detail.classList.add('hidden');document.body.classList.remove('modal-open')}
function save(id){const k=String(id);state.saved.has(k)?state.saved.delete(k):state.saved.add(k);localStorage.setItem('superdeal-saved',JSON.stringify([...state.saved]));render(filtered());toast.textContent=state.saved.has(k)?'Saved to your deals ♥':'Removed from saved';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');state.active=c.dataset.filter;sectionTitle.textContent=c.textContent.trim();render(filtered());loadIntelligence(state.deals)}));
searchEl.addEventListener('input',()=>{clearEl.classList.toggle('hidden',!searchEl.value);render(filtered())});clearEl.addEventListener('click',()=>{searchEl.value='';clearEl.classList.add('hidden');render(filtered());searchEl.focus()});
dealsEl.addEventListener('click',e=>{const saveBtn=e.target.closest('[data-save]');if(saveBtn){e.stopPropagation();save(saveBtn.dataset.save);return}const share=e.target.closest('[data-share]');if(share){e.stopPropagation();const d=state.deals.find(x=>String(x.id)===String(share.dataset.share));if(navigator.share)navigator.share({title:d.product_name,text:`${d.product_name} — ${money(d.current_price)}`,url:d.affiliate_url||d.source_url}).catch(()=>{});else navigator.clipboard?.writeText(d.affiliate_url||d.source_url||location.href);return}const open=e.target.closest('[data-open]');if(open)showDetail(open.dataset.open)});
detail.addEventListener('click',e=>{if(e.target.closest('[data-close]')||e.target===detail)closeDetail()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.nav==='search')searchEl.focus();if(b.dataset.nav==='saved'){state.active='saved';sectionTitle.textContent='Saved deals';render(filtered())}else if(b.dataset.nav==='home'){state.active='trending';document.querySelectorAll('.chip').forEach((x,i)=>x.classList.toggle('selected',i===0));sectionTitle.textContent='Trending now';render(filtered())}}));
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});load();